---
proxy_config:
  server_ipv4: "{{ ansible_default_ipv4['address'] }}"
  server_ipv6: "{{ ansible_default_ipv6['address'] }}"
  dns:
    - 1.1.1.1
    - 1.0.0.1
  port: 6677
  management:
    port: 8080
    user: "{{ proxy_management_user }}"
    enabled: "{{ proxy_enable_management }}"
  users: "{{ proxy_users_list }}"
proxy_ports:
  - port: "{{ proxy_config['port'] }}"
    enabled: yes
  - port: "{{ proxy_config['management']['port'] }}"
    enabled: "{{ proxy_config['management']['enabled'] }}"
service_name: "3proxy"
pid_dir: "/var/run/{{ service_name }}"
pid_file: "{{ pid_dir }}/{{ service_name }}.pid"
config_path: "/etc/{{ service_name }}.cfg"
service_path: "/usr/lib/systemd/system/{{ service_name }}.service"
...
