---

- name: Get group `nobody` ID
  getent:
    database: group
    key: nobody

- name: Get user `nobody` ID
  getent:
    database: passwd
    key: nobody

- name: Security tasks
  import_tasks: security.yml
  tags:
    - security

- name: Generate 3proxy config
  template:
    dest: "{{ config_path }}"
    src: "{{ service_name }}.cfg.j2"

- name: Generate 3proxy systemd service
  template:
    dest: "{{ service_path }}"
    src: "{{ service_name }}.service.j2"
  register: config_state
  tags:
    - config

- name: Set SELinux context for service file
  sefcontext:
    target: "{{ service_path }}"
    setype: systemd_unit_file_t
    state: present
  tags:
    - security
    - selinux

- name: Start 3proxy systemd service
  systemd:
    name: "{{ service_name }}.service"
    masked: no
    enabled: yes
    daemon_reload: yes
    state: "{{ 'restarted' if config_state is changed else 'started' }}"
  tags:
    - systemd
...
