---
- name: Main tasks
  block:
    - name: DNF tasks
      block:
        - import_tasks: dnf.yml
      tags:
        - dnf
    - name: Configuration 3proxy server
      import_tasks: 3proxy.yml
      become: yes
      tags:
        - configuration
  tags:
    - 3proxy
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
...
