---
- name: Open port for OpenVPN server
  firewalld:
    state: enabled
    permanent: yes
    port: "{{ openvpn_config['port'] }}/{{ openvpn_config['protocol'] }}"
  tags:
    - firewalld

- name: IPv4 forwading
  sysctl:
    name: net.ipv4.ip_forward
    state: present
    value: "1"
  tags:
    - sysctl

- name: Add trusted zone for tun device
  firewalld:
    zone: trusted
    permanent: yes
    interface: tun0
    state: enabled
  tags:
    - firewalld

- name: Enable masquerading
  firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
  tags:
    - firewalld

- name: Reload service `firewalld`
  systemd:
    state: reloaded
    name: firewalld
  tags:
    - firewalld
    - systemd

- name: Enable ports for OpenVPN
  seport:
    setype: openvpn_port_t
    ports: "{{ item['port'] }}"
    proto: tcp
  with_items: "{{ openvpn_ports }}"
  when: "item['enabled']"
  tags:
    - selinux
...
