---
- name: Create Nginx volumes directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ nginx_confd_path }}"
    - "{{ certbot_acme_path }}"
    - "{{ nginx_snippets_path }}"
  become: yes

...
