---
- name: Sysctl options
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  become: yes
  with_dict:
    net.core.somaxconn: 2000
    net.ipv6.conf.default.forwarding: 1
    net.ipv6.conf.all.forwarding: 1
...
