---
- name: Ansible preparation
  import_tasks: ansible.yml
  tags:
    - ansible

- name: Main tasks
  block:
    - name: DNF tasks
      import_tasks: dnf.yml
      tags:
        - dnf
    - name: Fail2ban task
      import_tasks: fail2ban.yml
      tags:
        - security
  tags:
    - common
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
...
