---
- name: Remove conflicted packages
  dnf:
    name: "{{ dnf_removed_packages }}"
    state: absent
  become: yes

- name: Install Docker related packages
  dnf:
    name: "{{ dnf_packages }}"
    state: latest
  become: yes
...
