---
- name: Main tasks
  block:
    - name: Configuration Docker-CE
      block:
        - import_tasks: common.yml
        - import_tasks: dnf.yml
          tags:
            - dnf
        - import_tasks: docker.yml
      become: yes
      tags:
        - configuration
  tags:
    - docker
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
...
